'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import Image from 'next/image';
import {Plus,Minus,Moon,Sun,BookOpen,GraduationCap,Check,Pause,ArchiveX,Pencil,X,ArrowUpRight,RefreshCw,LogOut,ChevronRight,BarChart3,LayoutGrid} from 'lucide-react';
import {STATES,TYPES,UNITS,type Item,type Snapshot,type State,type Review} from '@/lib/types';
import {addDays,localDay,weekStartFor,weekSummary} from '@/lib/analytics.mjs';

const EMPTY:Snapshot={items:[],events:[],reviews:[],timeZone:'Africa/Cairo'};
const blank=():Partial<Item>=>({title:'',type:'Book',state:'Parking',unit:'Pages',customUnit:'',current:0,total:null,coverFileId:'',resourceUrl:'',why:'',doneDefinition:'',nextStep:'',queuePosition:1});
const unit=(i:Item)=>i.unit==='Custom'?i.customUnit:i.unit.toLowerCase();
const pct=(i:Item)=>i.total?Math.min(100,100*i.current/i.total):0;
const fmt=(n:number)=>new Intl.NumberFormat('en',{maximumFractionDigits:2}).format(n);
async function api(url:string,options?:RequestInit){const r=await fetch(url,{cache:'no-store',...options});const d=await r.json();if(!r.ok)throw new Error(d.error||'The request failed.');return d;}

function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>{el?.close();};},[]);
 return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-labelledby="modal-title"><header><h2 id="modal-title">{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close"><X size={20}/></button></header>{children}</dialog>;
}
function Cover({item,small=false}:{item:Item;small?:boolean}){const [failed,setFailed]=useState(false);useEffect(()=>setFailed(false),[item.coverFileId]);return <div className={`cover ${small?'small':''} ${item.type==='Course'?'course':''}`}>{item.coverFileId&&!failed?<Image unoptimized src={'/api/cover/'+item.coverFileId} alt={item.title+' cover'} fill sizes={small?'48px':'82px'} onError={()=>setFailed(true)}/>:<><span>{item.type==='Course'?<GraduationCap size={small?20:24}/>:<BookOpen size={small?20:24}/>}</span>{!small&&<strong>{item.title}</strong>}</>}</div>;}
function Progress({item}:{item:Item}){return <><div className="progress-label"><span>{fmt(item.current)}{item.total?' / '+fmt(item.total):''} {unit(item)}</span><strong>{item.total?Math.round(pct(item))+'%':'Total not set'}</strong></div><div className="track" role="progressbar" aria-label={item.title+' progress'} aria-valuenow={item.current} aria-valuemin={0} aria-valuemax={item.total||undefined}><div style={{width:pct(item)+'%'}}/></div></>;}

export default function FocusApp({page}:{page:'board'|'analytics'}){
 const [session,setSession]=useState<{configured:boolean;authenticated:boolean}|null>(null),[data,setData]=useState<Snapshot>(EMPTY),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[dark,setDark]=useState(false),[demo,setDemo]=useState(false);
 const [editing,setEditing]=useState<Partial<Item>|null>(null),[queue,setQueue]=useState<State|null>(null),[completion,setCompletion]=useState<Item|null>(null);
 const [week,setWeek]=useState('');const retry=useRef<{action:string;payload:unknown;requestId:string}|null>(null);const inFlight=useRef(false);
 useEffect(()=>{setWeek(addDays(weekStartFor(localDay(new Date().toISOString())),-7));const saved=document.cookie.split('; ').find(v=>v.startsWith('focus_theme='))?.split('=')[1];setDark(saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches);api('/api/session').then(async s=>{setSession(s);if(s.authenticated)setData(await api('/api/data'));}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
 useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';},[dark]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(timer);},[notice]);
 async function refresh(){setLoading(true);setError('');try{setData(await api('/api/data'));retry.current=null;}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 async function mutate(action:string,payload:unknown,retryId?:string):Promise<boolean>{if(inFlight.current)return false;if(demo){setError('This is sample data. Sign in to save real resources and reviews.');return false;}inFlight.current=true;setBusy(true);setError('');const request={action,payload,requestId:retryId||crypto.randomUUID()};try{const result=await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});setData(result);retry.current=null;setNotice('Saved');return true;}catch(e){setError((e as Error).message);retry.current=request;return false;}finally{inFlight.current=false;setBusy(false);}}
 async function transition(item:Item,state:State){if(await mutate('state',{id:item.id,expectedVersion:item.version,state})){setCompletion(null);}}
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const phrase=new FormData(e.currentTarget).get('phrase');try{await api('/api/session',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phrase})});setSession({configured:true,authenticated:true});setDemo(false);await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function startDemo(){const w=addDays(weekStartFor(localDay(new Date().toISOString())),-7);const samples=[{...blank(),id:'demo-book',title:'Fundamentals of Software Engineering',state:'Main',type:'Book',current:92,total:286,nextStep:'Read the next section and capture one useful idea',version:1},{...blank(),id:'demo-course',title:'Advanced TypeScript Patterns',state:'Side',type:'Course',unit:'Lessons',current:7,total:18,nextStep:'Practice conditional types',version:1},{...blank(),id:'demo-park',title:'Designing Machine Learning Systems',type:'Book',state:'Parking',total:386,version:1}].map(i=>({...i,addedAt:new Date().toISOString(),startedAt:'',updatedAt:'',finishedAt:''})) as Item[];const events=[0,1,3,4,6].map((d,k)=>({id:'demo-'+k,requestId:'demo-'+k,itemId:samples[k%2].id,kind:'progress',at:addDays(w,d)+'T10:00:00Z',delta:k%2?2:10,unit:k%2?'Lessons':'Pages',fromState:samples[k%2].state,toState:samples[k%2].state,payload:samples[k%2]}));setData({...EMPTY,items:samples,events});setWeek(w);setDemo(true);setError('');}
 const main=data.items.find(i=>i.state==='Main'),side=data.items.find(i=>i.state==='Side');const parked=data.items.filter(i=>i.state==='Parking').sort((a,b)=>a.queuePosition-b.queuePosition||a.addedAt.localeCompare(b.addedAt));
 const summary=week?weekSummary(data.events,week,data.timeZone):null;
 const themeButton=<button className="icon-button" onClick={()=>{const value=!dark;setDark(value);document.cookie='focus_theme='+(value?'dark':'light')+'; Path=/; Max-Age=31536000; SameSite=Lax';}} aria-label={dark?'Switch to light theme':'Switch to dark theme'}>{dark?<Sun size={19}/>:<Moon size={19}/>}</button>;
 if(!session?.authenticated&&!demo)return <main className="gate"><div className="gate-theme">{themeButton}</div><div className="brand-mark">F</div><h1>Focus Shelf</h1><p>Explore freely. Start selectively.<br/>Finish deliberately.</p>{loading?<p role="status">Opening your shelf…</p>:<>{session?.configured?<form onSubmit={login}><label htmlFor="phrase">Your private access phrase</label><input id="phrase" name="phrase" type="password" autoComplete="current-password" required/><button className="primary" disabled={busy}>Open my shelf</button></form>:<div className="setup-note"><h2>Connection setup needed</h2><p>The app is ready for its Google Sheets connection. Complete the deployment settings to start saving your learning.</p></div>}<button className="text-button" onClick={startDemo}>Explore with sample data</button></>}{error&&<p role="alert" className="error">{error}</p>}</main>;
 return <div className="app-shell"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">F</span><strong>Focus Shelf</strong></Link><nav aria-label="Main navigation"><Link href="/" aria-current={page==='board'?'page':undefined}><LayoutGrid size={17}/>Focus board</Link><Link href="/analytics" aria-current={page==='analytics'?'page':undefined}><BarChart3 size={17}/>Analytics</Link></nav><div className="top-actions">{themeButton}<button className="primary add-button" disabled={busy||demo} onClick={()=>setEditing(blank())}><Plus size={18}/><span>Add resource</span></button><button className="icon-button" aria-label="Sign out" onClick={async()=>{if(!demo)await api('/api/session',{method:'DELETE'});setData(EMPTY);setDemo(false);setSession(s=>s?{...s,authenticated:false}:null);}}><LogOut size={18}/></button></div></header>
 <main className="content">{demo&&<div className="demo-banner">Sample data · sign in to save your own learning</div>}{error&&<div role="alert" className="error-banner"><span>{error}</span><div>{retry.current&&<button disabled={busy} onClick={()=>{const r=retry.current;if(r)void mutate(r.action,r.payload,r.requestId);}}>Retry save</button>}<button disabled={busy||demo} onClick={refresh}>Reload data</button><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={18}/></button></div></div>}
 {page==='board'?<><div className="page-heading"><div><h1>Your learning focus</h1><p>One main goal. One side goal. Everything else can wait.</p></div><button className="text-button" disabled={busy||loading||demo} onClick={refresh}><RefreshCw size={15} className={loading?'spin':''}/>Refresh</button></div><div className="slots">{(['Main','Side'] as const).map((name,idx)=><section key={name} className={'slot '+(idx?'side':'')}><div className="slot-heading"><h2><span className="slot-dot"/>{name} focus</h2><span className="badge">{(idx?side:main)?'1':'0'} of 1</span></div>{(idx?side:main)?<ResourceCard key={(idx?side:main)!.id+':'+(idx?side:main)!.version} item={(idx?side:main)!} busy={busy||demo} onEdit={()=>setEditing({...((idx?side:main)!)})} onProgress={current=>mutate('progress',{id:(idx?side:main)!.id,expectedVersion:(idx?side:main)!.version,current})} onState={state=>state==='Done'?setCompletion((idx?side:main)!):void transition((idx?side:main)!,state)}/>:<div className="empty-slot"><BookOpen size={28}/><h3>Your {name.toLowerCase()} slot is free</h3><p>Choose one resource worth your attention.</p><button disabled={busy||demo} onClick={()=>setQueue('Parking')}>Choose from Parking</button><button className="text-button" disabled={busy||demo} onClick={()=>setEditing({...blank(),state:name})}>Add something new</button></div>}</section>)}</div>
 <section className="parking"><div className="section-heading"><h2>Parking lot <span>{parked.length} waiting</span></h2><button className="text-button" onClick={()=>setQueue('Parking')}>View all <ChevronRight size={17}/></button></div>{parked.length?<div className="parking-grid">{parked.slice(0,3).map(item=><button key={item.id} className="park-card" onClick={()=>setEditing({...item})}><Cover item={item} small/><span><strong>{item.title}</strong><small>{item.type} · {item.current?fmt(item.current)+' '+unit(item):'Ready when you are'}</small></span><ChevronRight size={18}/></button>)}</div>:<div className="quiet-empty">A new book or course caught your eye? Add it here for later.</div>}</section><div className="shelf-links">{(['Paused','Done','Dropped'] as const).map(state=><button key={state} onClick={()=>setQueue(state)}>{state==='Done'?<Check size={16}/>:state==='Paused'?<Pause size={16}/>:<ArchiveX size={16}/>} {state} <span>{data.items.filter(i=>i.state===state).length}</span></button>)}</div></>:
 <><div className="page-heading"><div><h1>Your week in learning</h1><p>A little reflection. A clearer next step.</p></div><div className="week-picker"><label htmlFor="week">Sunday–Saturday · Cairo time</label><select id="week" value={week} onChange={e=>setWeek(e.target.value)}>{week&&Array.from({length:12},(_,n)=>addDays(weekStartFor(localDay(new Date().toISOString())),-n*7)).map(w=><option key={w} value={w}>{new Date(w+'T12:00:00Z').toLocaleDateString('en',{month:'short',day:'numeric'})} – {new Date(addDays(w,6)+'T12:00:00Z').toLocaleDateString('en',{month:'short',day:'numeric',year:'numeric'})}</option>)}</select></div></div>
 {summary&&<><dl className="stats"><div><dt>Active days</dt><dd>{summary.activeDays}<small> / 7</small></dd></div><div><dt>Resources advanced</dt><dd>{summary.advanced}</dd></div><div><dt>Completed</dt><dd>{summary.completed}</dd></div></dl><section className="panel"><h2>When you made progress</h2><p className="muted small-text">Days with positive progress updates.</p><div className="days">{summary.days.map((d:{day:string;active:boolean})=><div key={d.day} className={d.active?'active':''} aria-label={d.day+': '+(d.active?'Progress recorded':'No progress recorded')}><span>{new Date(d.day+'T12:00:00Z').toLocaleDateString('en',{weekday:'short'})}</span><div>{d.active?<Check size={18}/>:<Minus size={16}/>}</div><small>{new Date(d.day+'T12:00:00Z').getUTCDate()}</small></div>)}</div></section><div className="review-grid"><section className="panel"><h2>What moved forward</h2><p className="muted small-text">Net progress, with corrections included.</p>{summary.progress.length?summary.progress.map((g:{id:string;title:string;delta:number;unit:string})=><div className="weekly-item" key={g.id}><strong>{g.title}</strong><span>{g.delta>0?'+':''}{fmt(g.delta)} {g.unit.toLowerCase()}</span></div>):<div className="quiet-empty">No progress recorded this week. Your next small step can start here.</div>}<p className="muted small-text footnote">Pages, lessons, and hours stay separate.</p></section><section className="panel"><h2>Weekly reflection</h2><p className="muted small-text">Capture what matters for next week.</p><ReviewForm key={week+':'+(data.reviews.find(r=>r.weekStart===week)?.version||0)} review={data.reviews.find(r=>r.weekStart===week)} busy={busy||demo} save={values=>mutate('review',{...values,weekStart:week,expectedVersion:data.reviews.find(r=>r.weekStart===week)?.version||0})}/></section></div></>}
 </>}
 </main>{notice&&<div className="toast" role="status"><Check size={18}/>{notice}</div>}
 {editing&&<Modal title={editing.id?'Edit resource':'Add a learning resource'} onClose={()=>{if(!busy)setEditing(null);}}><ItemForm initial={editing} busy={busy||demo} items={data.items} onSave={async values=>{const saved=await mutate(editing.id?'update':'create',{...values,...(editing.id?{id:editing.id,expectedVersion:editing.version}:{})});if(saved)setEditing(null);return saved;}} onError={setError}/></Modal>}
 {queue&&<Modal title="Your learning shelf" onClose={()=>setQueue(null)}><div className="modal-body"><div className="queue-tabs">{(['Parking','Paused','Done','Dropped'] as State[]).map(s=><button key={s} aria-pressed={queue===s} onClick={()=>setQueue(s)}>{s}</button>)}</div><div className="queue-list">{data.items.filter(i=>i.state===queue).sort((a,b)=>a.queuePosition-b.queuePosition).map(item=><div className="queue-row" key={item.id}><Cover item={item} small/><div className="queue-copy"><strong>{item.title}</strong><small>{item.type} · {fmt(item.current)} {unit(item)}</small><div className="queue-actions"><button disabled={busy||demo||Boolean(main)} onClick={()=>transition(item,'Main')}>{main?'Main occupied':'To Main'}</button><button disabled={busy||demo||Boolean(side)} onClick={()=>transition(item,'Side')}>{side?'Side occupied':'To Side'}</button>{queue!=='Parking'&&<button disabled={busy||demo} onClick={()=>transition(item,'Parking')}>To Parking</button>}<button disabled={busy||demo} onClick={()=>{setQueue(null);setEditing({...item});}}>Edit</button></div></div></div>)}{!data.items.some(i=>i.state===queue)&&<div className="quiet-empty">Nothing here yet.</div>}</div></div></Modal>}
 {completion&&<Modal title="Finish deliberately" onClose={()=>setCompletion(null)}><div className="modal-body"><h3>{completion.title}</h3><p>Have you got the value you wanted from this resource?</p>{completion.doneDefinition&&<blockquote>{completion.doneDefinition}</blockquote>}<p className="muted">You can finish at {fmt(completion.current)} {unit(completion)}. Your recorded progress will stay as it is.</p><button className="primary" disabled={busy} onClick={()=>transition(completion,'Done')}><Check size={17}/>Mark as done</button></div></Modal>}
 </div>;
}

function ResourceCard({item,busy,onEdit,onProgress,onState}:{item:Item;busy:boolean;onEdit:()=>void;onProgress:(n:number)=>Promise<boolean>;onState:(s:State)=>void}){
 const [current,setCurrent]=useState(item.current);const step=['Pages','Chapters','Lessons'].includes(item.unit)?1:.5;
 return <><div className="resource"><Cover item={item}/><div className="resource-copy"><div className="resource-meta"><span>{item.type}</span><button className="icon-button" disabled={busy} onClick={onEdit} aria-label={'Edit '+item.title}><Pencil size={16}/></button></div><h3>{item.title}</h3><button className="next-step" disabled={busy} onClick={onEdit}><span>{item.nextStep?'Next: '+item.nextStep:'Add your next small step'}</span><Pencil size={14}/></button>{item.resourceUrl&&<a className="resource-link" href={item.resourceUrl} target="_blank" rel="noreferrer">Open resource <ArrowUpRight size={14}/></a>}</div></div><Progress item={item}/><form className="progress-form" onSubmit={e=>{e.preventDefault();void onProgress(current);}}><label htmlFor={'progress-'+item.id}>Update {unit(item)}</label><div><button type="button" className="icon-button" disabled={busy||current===0} aria-label="Decrease progress" onClick={()=>setCurrent(Math.max(0,current-step))}><Minus size={16}/></button><input id={'progress-'+item.id} type="number" min={0} max={item.total||undefined} step={step} value={current} onChange={e=>setCurrent(Number(e.target.value))} required disabled={busy}/><button type="button" className="icon-button" disabled={busy||(item.total!==null&&current>=item.total)} aria-label="Increase progress" onClick={()=>setCurrent(Math.min(item.total??Infinity,current+step))}><Plus size={16}/></button><button disabled={busy||current===item.current} type="submit">Save</button></div></form><div className="resource-actions"><button disabled={busy} onClick={()=>onState('Paused')}><Pause size={16}/>Pause</button><button className="success" disabled={busy} onClick={()=>onState('Done')}><Check size={16}/>Done</button><button className="danger" disabled={busy} onClick={()=>onState('Dropped')}><ArchiveX size={16}/>Drop</button></div></>;
}
function ReviewForm({review,busy,save}:{review?:Review;busy:boolean;save:(v:Partial<Review>)=>Promise<boolean>}){return <form className="review-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void save({learned:String(f.get('learned')),adjust:String(f.get('adjust')),nextStep:String(f.get('nextStep'))});}}><label>What did I learn or apply?<textarea name="learned" maxLength={4000} defaultValue={review?.learned} placeholder="One idea I can use in my work…"/></label><label>What should I continue or change?<textarea name="adjust" maxLength={4000} defaultValue={review?.adjust} placeholder="Keep, pause, or drop a focus? Why?"/></label><label>My next small step<textarea name="nextStep" maxLength={2000} defaultValue={review?.nextStep} placeholder="One realistic action for next week…"/></label><div className="review-footer"><button className="primary" disabled={busy}>Save review</button><small className="muted">{review?'Reviewed · '+localDay(review.updatedAt):'Not reviewed yet'}</small></div></form>;}
async function compressCover(file:File):Promise<{base64:string;mime:string}>{if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10000000)throw new Error('Choose a JPG, PNG, or WebP image under 10 MB.');const bitmap=await createImageBitmap(file);const scale=Math.min(1,800/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d')!;context.fillStyle='#ffffff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();const data=canvas.toDataURL('image/jpeg',.8);if(data.length>660000)throw new Error('Please choose a smaller cover image.');return {base64:data.split(',')[1],mime:'image/jpeg'};}
function ItemForm({initial,busy,items,onSave,onError}:{initial:Partial<Item>;busy:boolean;items:Item[];onSave:(v:Partial<Item>)=>Promise<boolean>;onError:(s:string)=>void}){
 const [draft,setDraft]=useState(initial),[uploading,setUploading]=useState(false),[formError,setFormError]=useState('');
 const set=(key:keyof Item,value:unknown)=>setDraft(p=>({...p,[key]:value}));
 async function upload(file?:File){if(!file)return;setUploading(true);setFormError('');try{const payload=await compressCover(file);const result=await api('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'uploadCover',payload,requestId:crypto.randomUUID()})});set('coverFileId',result.fileId);}catch(e){setFormError((e as Error).message);}finally{setUploading(false);}}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setFormError('');if(draft.total!==null&&Number(draft.current)>Number(draft.total)){setFormError('Progress cannot exceed total.');return;}try{if(!await onSave(draft))setFormError('This change was not saved. Review the message above and retry.');}catch(e){const message=(e as Error).message;setFormError(message);onError(message);}}
 return <form onSubmit={submit}>
  <div className="modal-body form-grid">
   <label className="full">Title<input value={draft.title} maxLength={240} required autoFocus onChange={e=>set('title',e.target.value)}/></label>
   <label>Type<select value={draft.type} onChange={e=>set('type',e.target.value)}>{TYPES.map(t=><option key={t}>{t}</option>)}</select></label>
   {!draft.id&&<label>Add to<select value={draft.state} onChange={e=>set('state',e.target.value)}>{STATES.filter(s=>!['Done','Dropped'].includes(s)).map(s=><option key={s} disabled={['Main','Side'].includes(s)&&items.some(i=>i.state===s)}>{s}</option>)}</select></label>}
   <label>Progress unit<select value={draft.unit} disabled={Boolean(draft.id&&draft.current)} onChange={e=>{set('unit',e.target.value);if(e.target.value==='Percent')set('total',100);}}>{UNITS.map(u=><option key={u}>{u}</option>)}</select></label>
   {draft.unit==='Custom'&&<label>Unit name<input required maxLength={30} value={draft.customUnit} disabled={Boolean(draft.id&&draft.current)} onChange={e=>set('customUnit',e.target.value)}/></label>}
   <label>Total (optional)<input type="number" min={.01} step="any" disabled={draft.unit==='Percent'} value={draft.total??''} onChange={e=>set('total',e.target.value===''?null:Number(e.target.value))} placeholder="Unknown? Leave blank"/></label>
   {!draft.id&&<label>Already completed<input type="number" min={0} step="any" value={draft.current} onChange={e=>set('current',Number(e.target.value))}/></label>}
   <label className="full">Cover image (optional)<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||uploading} onChange={e=>void upload(e.target.files?.[0])}/><small className="muted">{uploading?'Uploading…':draft.coverFileId?'Cover uploaded.':'A default cover appears when no image is added.'}</small>{draft.coverFileId&&<button type="button" className="text-button" onClick={()=>set('coverFileId','')}>Remove cover</button>}</label>
   <label className="full">Resource link (optional)<input type="url" value={draft.resourceUrl} maxLength={2048} onChange={e=>set('resourceUrl',e.target.value)} placeholder="https://…"/></label>
   <label className="full">Next small step<input value={draft.nextStep} maxLength={1000} onChange={e=>set('nextStep',e.target.value)} placeholder="Read 5 pages and capture one key idea"/></label>
   <details className="full"><summary>Purpose and queue order</summary><label>Why does this matter?<textarea value={draft.why} maxLength={2000} onChange={e=>set('why',e.target.value)}/></label><label>I’ll consider it done when…<textarea value={draft.doneDefinition} maxLength={2000} onChange={e=>set('doneDefinition',e.target.value)}/></label><label>Queue position<input type="number" min={0} step={1} value={draft.queuePosition} onChange={e=>set('queuePosition',Number(e.target.value))}/></label></details>
   {formError&&<p className="error full" role="alert">{formError}</p>}
  </div>
  <footer className="modal-footer"><button className="primary" disabled={busy||uploading}>{busy?'Saving…':draft.id?'Save changes':'Add resource'}</button></footer>
 </form>;
}
